<!DOCTYPE html
  PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>API docs for &ldquo;vmc.contrib.axiom.errors&rdquo;</title>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
    <link href="apidocs.css" type="text/css" rel="stylesheet" />
    
    
  </head>
  <body>
    <h1 class="module">Module v.c.a.errors</h1>
    <p>
      <span id="part">Part of <a href="vmc.html">vmc</a>.<a href="vmc.contrib.html">contrib</a>.<a href="vmc.contrib.axiom.html">axiom</a></span>
      
      
    </p>
    <div>
      
    </div>
    <div class="undocumented">No module docstring</div>
    
    
    <div id="splitTables">
      <table class="children sortable" id="id428">
  
  
  
  
  <tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.TimeoutError.html">TimeoutError</a></td>
    <td><span>A low-level SQL operation timed out.
</span></td>
  </tr><tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.BadCredentials.html">BadCredentials</a></td>
    <td><span class="undocumented">Undocumented</span></td>
  </tr><tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.NoSuchUser.html">NoSuchUser</a></td>
    <td><span class="undocumented">Undocumented</span></td>
  </tr><tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.MissingDomainPart.html">MissingDomainPart</a></td>
    <td><span>Raised when a login is attempted with a username which consists of 
only
</span></td>
  </tr><tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.DuplicateUser.html">DuplicateUser</a></td>
    <td><span class="undocumented">Undocumented</span></td>
  </tr><tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.CannotOpenStore.html">CannotOpenStore</a></td>
    <td><span>There is a problem such that the store cannot be opened.
</span></td>
  </tr><tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.NoUpgradePathAvailable.html">NoUpgradePathAvailable</a></td>
    <td><span>No upgrade path is available, so the store cannot be opened.
</span></td>
  </tr><tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.NoCrossStoreReferences.html">NoCrossStoreReferences</a></td>
    <td><span>References are not allowed between items within different Stores.
</span></td>
  </tr><tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.SQLError.html">SQLError</a></td>
    <td><span>Axiom internally generated some bad SQL.
</span></td>
  </tr><tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.TableAlreadyExists.html">TableAlreadyExists</a></td>
    <td><span>Axiom internally created a table at the same time as another 
database.
</span></td>
  </tr><tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.UnknownItemType.html">UnknownItemType</a></td>
    <td><span>Can't load an item: it's of a type that I don't see anywhere in 
Python.
</span></td>
  </tr><tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.SQLWarning.html">SQLWarning</a></td>
    <td><span>Axiom internally generated some CREATE TABLE SQL that ... probably 
wasn't bad
</span></td>
  </tr><tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.TableCreationConcurrencyError.html">TableCreationConcurrencyError</a></td>
    <td><span>Woah, this is really bad.  If you can get this please tell us how.
</span></td>
  </tr><tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.DuplicateUniqueItem.html">DuplicateUniqueItem</a></td>
    <td><span>Found 2 or more of an item which is supposed to be unique.
</span></td>
  </tr><tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.ItemNotFound.html">ItemNotFound</a></td>
    <td><span>Did not find even 1 of an item which was supposed to exist.
</span></td>
  </tr><tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.ItemClassesOnly.html">ItemClassesOnly</a></td>
    <td><span>An object was passed to a method that wasn't a subclass of Item.
</span></td>
  </tr><tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.ChangeRejected.html">ChangeRejected</a></td>
    <td><span>Raised when an attempt is made to change the database at a time when
</span></td>
  </tr><tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.DependencyError.html">DependencyError</a></td>
    <td><span>Raised when an item can't be installed or uninstalled.
</span></td>
  </tr><tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.DeletionDisallowed.html">DeletionDisallowed</a></td>
    <td><span>Raised when an attempt is made to delete an item that is referred to 
by
</span></td>
  </tr><tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.DataIntegrityError.html">DataIntegrityError</a></td>
    <td><span>Data integrity seems to have been lost.
</span></td>
  </tr><tr class="class">
    
    
    <td>Class</td>
    <td><a href="vmc.contrib.axiom.errors.BrokenReference.html">BrokenReference</a></td>
    <td><span>A reference to a nonexistent item was detected when this should be
</span></td>
  </tr>
  
</table>
      
      
    </div>
    
    
    
    
    
    <address>
      <a href="index.html">API Documentation</a> for vodafone-mobile-connect-card-driver-for-linux, generated by <a href="http://codespeak.net/~mwh/pydoctor/">pydoctor</a> at 2008-01-10 13:06:31.
    </address>
  </body>
</html>